
name: build-and-test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libjson-c-dev \
            libpulse-dev \
            libsndfile1-dev \
            libinput-dev \
            libevdev-dev \
            libudev-dev

      - name: Build
        run: make -j$(nproc)

      - name: List sound packs
        run: ./keyvibe --list

      - name: Smoke test help
        run: ./keyvibe --help || true


