
name: build-and-test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libjson-c-dev \
            libpulse-dev \
            libsndfile1-dev \
            libinput-dev \
            libevdev-dev \
            libudev-dev

      - name: Build (with repo-local PREFIX)
        run: make -j$(nproc) PREFIX=$PWD

      - name: Prepare data dir for runtime
        run: |
          mkdir -p "$PWD/share/vbx"
          cp -r audio "$PWD/share/vbx/"

      - name: List sound packs
        run: ./vbx --list

      - name: Smoke test help
        run: ./vbx --help || true

      - name: Extra smoke tests (non-fatal)
        run: |
          ./vbx --reload || true
          ./vbx --stop || true

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: vbx-binaries
          path: |
            vbx
            vbx-audio
            vbx-input


